title: Justin Bisuna
logo: /assets/img/Justin_Bisuna_Portrait.png

# show_downloads: true
theme: jekyll-theme-minimal

# OTHER THEMES
# Architect
# Cayman
# Dinky
# Hacker
# Leap day
# Midnight
# Minima
# Minimal
# Modernist
# Slate
# Tactile
# Time machine
